version: '3.1'

services:
    proxy:
        build: .
        network_mode: bridge
        ports:
            - 3128:3128
            - 8128:80
        volumes:
            - ./cntlm.conf:/etc/cntlm.conf

